In [14]:
! pip install pandas
! pip install requests
! pip install numpy
! pip install beautifulsoup4


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
import pandas as pd
import numpy as np
import requests
import imdb
from bs4 import BeautifulSoup as bs
import csv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [16]:
file_path = r'C:\Users\Admin\Desktop\JP\Web scrapping\movie_info2.csv'
df = pd.read_csv(file_path, encoding='ISO-8859-1')

In [17]:
df

Movie Name    Imdb_id  Rating Release Date  \
0             3 Idiots  tt1187043     8.4         2009   
1     Taare Zameen Par  tt0986264     8.3         2007   
2                   PK  tt2338151     8.1         2014   
3               Dangal  tt5074352     8.3         2016   
4      Rang De Basanti  tt0405508     8.1         2006   
...                ...        ...     ...          ...   
3531           Mehmaan  tt0213879     5.7      IMDbPro   
3532       Sorry Daddy  tt4994210     6.0      IMDbPro   
3533  Raadha Aur Seeta  tt0378633     6.3         1979   
3534   IPC Section 302  tt0359129     4.7         1975   
3535           Calapor  tt3311236     5.2         2013   

                      Genres  \
0               Comedy,Drama   
1               Drama,Family   
2        Comedy,Drama,Sci-Fi   
3     Action,Biography,Drama   
4         Comedy,Crime,Drama   
...                      ...   
3531      Action,Crime,Drama   
3532                  Action   
3533            Drama,Family   
3534           Drama,Mystery   
3535                   Drama   

                                                   Cast  
0     Aamir Khan,Madhavan,Mona Singh,Sharman Joshi,K...  
1     Darsheel Safary,Aamir Khan,Tanay Chheda,Sachet...  
2     Aamir Khan,Anushka Sharma,Sanjay Dutt,Boman Ir...  
3     Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sa...  
4     Aamir Khan,Soha Ali Khan,Siddharth,Sharman Jos...  
...                                                 ...  
3531  Biswajeet Chatterjee,Rekha,Sulochana Latkar,Ma...  
3532  Shamim Khan,Tahir Kamaal Khan,Anupam Shukla,Mu...  
3533  Rajendranath Malhotra,Madan Puri,Leela Mishra,...  
3534  Randhir Kapoor,Rekha,Ajit Khan,Ashok Kumar,Pre...  
3535       Hemant Gopal,Trisha Patil,Rituparna Sengupta  

[3536 rows x 6 columns]

In [18]:
df.isna().sum()

Movie Name        0
Imdb_id           0
Rating          272
Release Date      3
Genres           96
Cast            156
dtype: int64

In [19]:
df['Rating'].fillna(0, inplace=True)
df['Cast'].fillna("Unknown", inplace=True)
df['Release Date'].fillna("000", inplace=True)
df['Genres'].fillna("General", inplace=True)


In [20]:
df.isna().sum()

Movie Name      0
Imdb_id         0
Rating          0
Release Date    0
Genres          0
Cast            0
dtype: int64

In [21]:
Tfidf=TfidfVectorizer()

In [22]:
vectors=Tfidf.fit_transform(df['Genres'])

In [23]:
vectors[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.84347259,
        0.        , 0.        , 0.53717222, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [37]:
indexed=pd.Series(index=df["Movie Name"],data=df.index)

In [38]:
indexed

Movie Name
3 Idiots               0
Taare Zameen Par       1
PK                     2
Dangal                 3
Rang De Basanti        4
                    ... 
Mehmaan             3531
Sorry Daddy         3532
Raadha Aur Seeta    3533
IPC Section 302     3534
Calapor             3535
Length: 3536, dtype: int64

In [39]:
indexed["3 Idiots"]

0

In [32]:
vectors[2].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.24993254,
        0.        , 0.        , 0.15917153, 0.        , 0.        ,
        0.67535107, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.67535107, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [44]:
dis=linear_kernel(vectors[600],vectors)

In [45]:
dis

array([[0.58138015, 0.        , 0.17227094, ..., 0.        , 0.        ,
        0.        ]])

In [46]:
score=pd.DataFrame(dis)

In [47]:
score

0     1         2     3         4     5         6     7         8     \
0  0.58138   0.0  0.172271   0.0  0.396865   0.0  0.346331   0.0  0.366388   

       9     ...  3526      3527      3528  3529  3530  3531  3532  3533  \
0  0.366388  ...   0.0  0.724505  0.619643   0.0   0.0   0.0   0.0   0.0   

   3534  3535  
0   0.0   0.0  

[1 rows x 3536 columns]

In [48]:
transpose_score=score.T

In [49]:
transpose_score

0
0     0.581380
1     0.000000
2     0.172271
3     0.000000
4     0.396865
...        ...
3531  0.000000
3532  0.000000
3533  0.000000
3534  0.000000
3535  0.000000

[3536 rows x 1 columns]

In [50]:
transpose_score.columns=["scores"]

In [51]:
transpose_score

scores
0     0.581380
1     0.000000
2     0.172271
3     0.000000
4     0.396865
...        ...
3531  0.000000
3532  0.000000
3533  0.000000
3534  0.000000
3535  0.000000

[3536 rows x 1 columns]

In [53]:
df["Movie Name"][787]

'Raaz Reboot'

In [58]:
def movie_recomm(name,n):
    dis=linear_kernel(vectors[indexed[name]],vectors)
    scores=pd.DataFrame(dis).T
    scores.columns=["Score"]
    scores=scores.sort_values('Score',ascending=False)
    
    list=[]
    for i in range(0 , n+1):
        s={
            "title":df["Movie Name"][scores.index[i]],
            'rating':df['Rating'][scores.index[i]],
            'genre':df["Genres"][scores.index[i]]
        }
        list.append(s)
    
    
    return list

In [60]:
pd.DataFrame(movie_recomm("Raaz Reboot",5))

title  rating                   genre
0                  Raaz Reboot     4.4  Horror,Mystery,Romance
1                         1920     6.4  Horror,Mystery,Romance
2              Krishna Cottage     5.2  Horror,Mystery,Romance
3                 Kucch To Hai     4.3  Horror,Mystery,Romance
4  Raaz: The Mystery Continues     5.7  Horror,Mystery,Romance
5                       Censor     6.0          Horror,Mystery

In [67]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]}
df = pd.DataFrame(data, index=['row1', 'row2', 'row3', 'row4'])

# Select a single element by label
element = df.loc['row2', 'A']  # Selects the value in row 'row2' and column 'A'
# print(element,"Element")  # Output: 2

# Select a row by label
row = df.loc['row3']  # Selects the entire row with label 'row3'
print(row,"row")


A    3
B    7
Name: row3, dtype: int64 row


In [66]:
df

A  B
row1  1  5
row2  2  6
row3  3  7
row4  4  8

In [68]:
subset = df.loc[['row1', 'row3'], ['A', 'B']]
print(subset)

      A  B
row1  1  5
row3  3  7


In [69]:
element = df.iloc[1, 0]  # Selects the value at row 1 and column 0 (0-based index)
print(element)  # Output: 2

2


In [70]:
row = df.iloc[2]  # Selects the entire row at position 2 (0-based index)
print(row)

A    3
B    7
Name: row3, dtype: int64
